/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAuthedRouteImport } from './routes/dashboard/_authed'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as DashboardAuthedTeamIndexRouteImport } from './routes/dashboard/_authed/team/index'
import { Route as DashboardAuthedAdminIndexRouteImport } from './routes/dashboard/_authed/admin/index'
import { Route as AuthRegisterTeamIdIndexRouteImport } from './routes/auth/register/$teamId/index'
import { Route as AuthRegisterTeamIdCompletedRouteImport } from './routes/auth/register/$teamId/completed'
import { Route as DashboardAuthedAdminTeamsIndexRouteImport } from './routes/dashboard/_authed/admin/teams/index'
import { Route as DashboardAuthedAdminSubmissionsIndexRouteImport } from './routes/dashboard/_authed/admin/submissions/index'
import { Route as DashboardAuthedAdminScoreboardIndexRouteImport } from './routes/dashboard/_authed/admin/scoreboard/index'
import { Route as DashboardAuthedAdminExamsIndexRouteImport } from './routes/dashboard/_authed/admin/exams/index'
import { Route as DashboardAuthedAdminCompetitionsIndexRouteImport } from './routes/dashboard/_authed/admin/competitions/index'
import { Route as DashboardAuthedAdminTeamsTeamIdRouteImport } from './routes/dashboard/_authed/admin/teams/$teamId'
import { Route as DashboardAuthedTeamExamExamIdIndexRouteImport } from './routes/dashboard/_authed/team/exam/$examId/index'
import { Route as DashboardAuthedAdminExamsExamIdIndexRouteImport } from './routes/dashboard/_authed/admin/exams/$examId/index'
import { Route as DashboardAuthedTeamExamExamIdReviewRouteImport } from './routes/dashboard/_authed/team/exam/$examId/review'
import { Route as DashboardAuthedAdminExamsExamIdReviewsRouteImport } from './routes/dashboard/_authed/admin/exams/$examId/reviews'
import { Route as DashboardAuthedAdminExamsExamIdSessionsIndexRouteImport } from './routes/dashboard/_authed/admin/exams/$examId/sessions/index'
import { Route as DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRouteImport } from './routes/dashboard/_authed/admin/exams/$examId/attempts/$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthedRoute = DashboardAuthedRouteImport.update({
  id: '/dashboard/_authed',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthedTeamIndexRoute =
  DashboardAuthedTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminIndexRoute =
  DashboardAuthedAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const AuthRegisterTeamIdIndexRoute = AuthRegisterTeamIdIndexRouteImport.update({
  id: '/auth/register/$teamId/',
  path: '/auth/register/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterTeamIdCompletedRoute =
  AuthRegisterTeamIdCompletedRouteImport.update({
    id: '/auth/register/$teamId/completed',
    path: '/auth/register/$teamId/completed',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAuthedAdminTeamsIndexRoute =
  DashboardAuthedAdminTeamsIndexRouteImport.update({
    id: '/admin/teams/',
    path: '/admin/teams/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminSubmissionsIndexRoute =
  DashboardAuthedAdminSubmissionsIndexRouteImport.update({
    id: '/admin/submissions/',
    path: '/admin/submissions/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminScoreboardIndexRoute =
  DashboardAuthedAdminScoreboardIndexRouteImport.update({
    id: '/admin/scoreboard/',
    path: '/admin/scoreboard/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminExamsIndexRoute =
  DashboardAuthedAdminExamsIndexRouteImport.update({
    id: '/admin/exams/',
    path: '/admin/exams/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminCompetitionsIndexRoute =
  DashboardAuthedAdminCompetitionsIndexRouteImport.update({
    id: '/admin/competitions/',
    path: '/admin/competitions/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminTeamsTeamIdRoute =
  DashboardAuthedAdminTeamsTeamIdRouteImport.update({
    id: '/admin/teams/$teamId',
    path: '/admin/teams/$teamId',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedTeamExamExamIdIndexRoute =
  DashboardAuthedTeamExamExamIdIndexRouteImport.update({
    id: '/team/exam/$examId/',
    path: '/team/exam/$examId/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminExamsExamIdIndexRoute =
  DashboardAuthedAdminExamsExamIdIndexRouteImport.update({
    id: '/admin/exams/$examId/',
    path: '/admin/exams/$examId/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedTeamExamExamIdReviewRoute =
  DashboardAuthedTeamExamExamIdReviewRouteImport.update({
    id: '/team/exam/$examId/review',
    path: '/team/exam/$examId/review',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminExamsExamIdReviewsRoute =
  DashboardAuthedAdminExamsExamIdReviewsRouteImport.update({
    id: '/admin/exams/$examId/reviews',
    path: '/admin/exams/$examId/reviews',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminExamsExamIdSessionsIndexRoute =
  DashboardAuthedAdminExamsExamIdSessionsIndexRouteImport.update({
    id: '/admin/exams/$examId/sessions/',
    path: '/admin/exams/$examId/sessions/',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)
const DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute =
  DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRouteImport.update({
    id: '/admin/exams/$examId/attempts/$attemptId',
    path: '/admin/exams/$examId/attempts/$attemptId',
    getParentRoute: () => DashboardAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardAuthedRouteWithChildren
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/register/$teamId/completed': typeof AuthRegisterTeamIdCompletedRoute
  '/auth/register/$teamId/': typeof AuthRegisterTeamIdIndexRoute
  '/dashboard/admin/': typeof DashboardAuthedAdminIndexRoute
  '/dashboard/team/': typeof DashboardAuthedTeamIndexRoute
  '/dashboard/admin/teams/$teamId': typeof DashboardAuthedAdminTeamsTeamIdRoute
  '/dashboard/admin/competitions/': typeof DashboardAuthedAdminCompetitionsIndexRoute
  '/dashboard/admin/exams/': typeof DashboardAuthedAdminExamsIndexRoute
  '/dashboard/admin/scoreboard/': typeof DashboardAuthedAdminScoreboardIndexRoute
  '/dashboard/admin/submissions/': typeof DashboardAuthedAdminSubmissionsIndexRoute
  '/dashboard/admin/teams/': typeof DashboardAuthedAdminTeamsIndexRoute
  '/dashboard/admin/exams/$examId/reviews': typeof DashboardAuthedAdminExamsExamIdReviewsRoute
  '/dashboard/team/exam/$examId/review': typeof DashboardAuthedTeamExamExamIdReviewRoute
  '/dashboard/admin/exams/$examId/': typeof DashboardAuthedAdminExamsExamIdIndexRoute
  '/dashboard/team/exam/$examId/': typeof DashboardAuthedTeamExamExamIdIndexRoute
  '/dashboard/admin/exams/$examId/attempts/$attemptId': typeof DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute
  '/dashboard/admin/exams/$examId/sessions/': typeof DashboardAuthedAdminExamsExamIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardAuthedRouteWithChildren
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/register/$teamId/completed': typeof AuthRegisterTeamIdCompletedRoute
  '/auth/register/$teamId': typeof AuthRegisterTeamIdIndexRoute
  '/dashboard/admin': typeof DashboardAuthedAdminIndexRoute
  '/dashboard/team': typeof DashboardAuthedTeamIndexRoute
  '/dashboard/admin/teams/$teamId': typeof DashboardAuthedAdminTeamsTeamIdRoute
  '/dashboard/admin/competitions': typeof DashboardAuthedAdminCompetitionsIndexRoute
  '/dashboard/admin/exams': typeof DashboardAuthedAdminExamsIndexRoute
  '/dashboard/admin/scoreboard': typeof DashboardAuthedAdminScoreboardIndexRoute
  '/dashboard/admin/submissions': typeof DashboardAuthedAdminSubmissionsIndexRoute
  '/dashboard/admin/teams': typeof DashboardAuthedAdminTeamsIndexRoute
  '/dashboard/admin/exams/$examId/reviews': typeof DashboardAuthedAdminExamsExamIdReviewsRoute
  '/dashboard/team/exam/$examId/review': typeof DashboardAuthedTeamExamExamIdReviewRoute
  '/dashboard/admin/exams/$examId': typeof DashboardAuthedAdminExamsExamIdIndexRoute
  '/dashboard/team/exam/$examId': typeof DashboardAuthedTeamExamExamIdIndexRoute
  '/dashboard/admin/exams/$examId/attempts/$attemptId': typeof DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute
  '/dashboard/admin/exams/$examId/sessions': typeof DashboardAuthedAdminExamsExamIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/_authed': typeof DashboardAuthedRouteWithChildren
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/register/$teamId/completed': typeof AuthRegisterTeamIdCompletedRoute
  '/auth/register/$teamId/': typeof AuthRegisterTeamIdIndexRoute
  '/dashboard/_authed/admin/': typeof DashboardAuthedAdminIndexRoute
  '/dashboard/_authed/team/': typeof DashboardAuthedTeamIndexRoute
  '/dashboard/_authed/admin/teams/$teamId': typeof DashboardAuthedAdminTeamsTeamIdRoute
  '/dashboard/_authed/admin/competitions/': typeof DashboardAuthedAdminCompetitionsIndexRoute
  '/dashboard/_authed/admin/exams/': typeof DashboardAuthedAdminExamsIndexRoute
  '/dashboard/_authed/admin/scoreboard/': typeof DashboardAuthedAdminScoreboardIndexRoute
  '/dashboard/_authed/admin/submissions/': typeof DashboardAuthedAdminSubmissionsIndexRoute
  '/dashboard/_authed/admin/teams/': typeof DashboardAuthedAdminTeamsIndexRoute
  '/dashboard/_authed/admin/exams/$examId/reviews': typeof DashboardAuthedAdminExamsExamIdReviewsRoute
  '/dashboard/_authed/team/exam/$examId/review': typeof DashboardAuthedTeamExamExamIdReviewRoute
  '/dashboard/_authed/admin/exams/$examId/': typeof DashboardAuthedAdminExamsExamIdIndexRoute
  '/dashboard/_authed/team/exam/$examId/': typeof DashboardAuthedTeamExamExamIdIndexRoute
  '/dashboard/_authed/admin/exams/$examId/attempts/$attemptId': typeof DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute
  '/dashboard/_authed/admin/exams/$examId/sessions/': typeof DashboardAuthedAdminExamsExamIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/dashboard'
    | '/auth/register/'
    | '/auth/register/$teamId/completed'
    | '/auth/register/$teamId/'
    | '/dashboard/admin/'
    | '/dashboard/team/'
    | '/dashboard/admin/teams/$teamId'
    | '/dashboard/admin/competitions/'
    | '/dashboard/admin/exams/'
    | '/dashboard/admin/scoreboard/'
    | '/dashboard/admin/submissions/'
    | '/dashboard/admin/teams/'
    | '/dashboard/admin/exams/$examId/reviews'
    | '/dashboard/team/exam/$examId/review'
    | '/dashboard/admin/exams/$examId/'
    | '/dashboard/team/exam/$examId/'
    | '/dashboard/admin/exams/$examId/attempts/$attemptId'
    | '/dashboard/admin/exams/$examId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard'
    | '/auth/register'
    | '/auth/register/$teamId/completed'
    | '/auth/register/$teamId'
    | '/dashboard/admin'
    | '/dashboard/team'
    | '/dashboard/admin/teams/$teamId'
    | '/dashboard/admin/competitions'
    | '/dashboard/admin/exams'
    | '/dashboard/admin/scoreboard'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/teams'
    | '/dashboard/admin/exams/$examId/reviews'
    | '/dashboard/team/exam/$examId/review'
    | '/dashboard/admin/exams/$examId'
    | '/dashboard/team/exam/$examId'
    | '/dashboard/admin/exams/$examId/attempts/$attemptId'
    | '/dashboard/admin/exams/$examId/sessions'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/dashboard/_authed'
    | '/auth/register/'
    | '/auth/register/$teamId/completed'
    | '/auth/register/$teamId/'
    | '/dashboard/_authed/admin/'
    | '/dashboard/_authed/team/'
    | '/dashboard/_authed/admin/teams/$teamId'
    | '/dashboard/_authed/admin/competitions/'
    | '/dashboard/_authed/admin/exams/'
    | '/dashboard/_authed/admin/scoreboard/'
    | '/dashboard/_authed/admin/submissions/'
    | '/dashboard/_authed/admin/teams/'
    | '/dashboard/_authed/admin/exams/$examId/reviews'
    | '/dashboard/_authed/team/exam/$examId/review'
    | '/dashboard/_authed/admin/exams/$examId/'
    | '/dashboard/_authed/team/exam/$examId/'
    | '/dashboard/_authed/admin/exams/$examId/attempts/$attemptId'
    | '/dashboard/_authed/admin/exams/$examId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardAuthedRoute: typeof DashboardAuthedRouteWithChildren
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthRegisterTeamIdCompletedRoute: typeof AuthRegisterTeamIdCompletedRoute
  AuthRegisterTeamIdIndexRoute: typeof AuthRegisterTeamIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authed': {
      id: '/dashboard/_authed'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authed/team/': {
      id: '/dashboard/_authed/team/'
      path: '/team'
      fullPath: '/dashboard/team/'
      preLoaderRoute: typeof DashboardAuthedTeamIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/': {
      id: '/dashboard/_authed/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAuthedAdminIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/auth/register/$teamId/': {
      id: '/auth/register/$teamId/'
      path: '/auth/register/$teamId'
      fullPath: '/auth/register/$teamId/'
      preLoaderRoute: typeof AuthRegisterTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/$teamId/completed': {
      id: '/auth/register/$teamId/completed'
      path: '/auth/register/$teamId/completed'
      fullPath: '/auth/register/$teamId/completed'
      preLoaderRoute: typeof AuthRegisterTeamIdCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authed/admin/teams/': {
      id: '/dashboard/_authed/admin/teams/'
      path: '/admin/teams'
      fullPath: '/dashboard/admin/teams/'
      preLoaderRoute: typeof DashboardAuthedAdminTeamsIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/submissions/': {
      id: '/dashboard/_authed/admin/submissions/'
      path: '/admin/submissions'
      fullPath: '/dashboard/admin/submissions/'
      preLoaderRoute: typeof DashboardAuthedAdminSubmissionsIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/scoreboard/': {
      id: '/dashboard/_authed/admin/scoreboard/'
      path: '/admin/scoreboard'
      fullPath: '/dashboard/admin/scoreboard/'
      preLoaderRoute: typeof DashboardAuthedAdminScoreboardIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/exams/': {
      id: '/dashboard/_authed/admin/exams/'
      path: '/admin/exams'
      fullPath: '/dashboard/admin/exams/'
      preLoaderRoute: typeof DashboardAuthedAdminExamsIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/competitions/': {
      id: '/dashboard/_authed/admin/competitions/'
      path: '/admin/competitions'
      fullPath: '/dashboard/admin/competitions/'
      preLoaderRoute: typeof DashboardAuthedAdminCompetitionsIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/teams/$teamId': {
      id: '/dashboard/_authed/admin/teams/$teamId'
      path: '/admin/teams/$teamId'
      fullPath: '/dashboard/admin/teams/$teamId'
      preLoaderRoute: typeof DashboardAuthedAdminTeamsTeamIdRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/team/exam/$examId/': {
      id: '/dashboard/_authed/team/exam/$examId/'
      path: '/team/exam/$examId'
      fullPath: '/dashboard/team/exam/$examId/'
      preLoaderRoute: typeof DashboardAuthedTeamExamExamIdIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/exams/$examId/': {
      id: '/dashboard/_authed/admin/exams/$examId/'
      path: '/admin/exams/$examId'
      fullPath: '/dashboard/admin/exams/$examId/'
      preLoaderRoute: typeof DashboardAuthedAdminExamsExamIdIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/team/exam/$examId/review': {
      id: '/dashboard/_authed/team/exam/$examId/review'
      path: '/team/exam/$examId/review'
      fullPath: '/dashboard/team/exam/$examId/review'
      preLoaderRoute: typeof DashboardAuthedTeamExamExamIdReviewRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/exams/$examId/reviews': {
      id: '/dashboard/_authed/admin/exams/$examId/reviews'
      path: '/admin/exams/$examId/reviews'
      fullPath: '/dashboard/admin/exams/$examId/reviews'
      preLoaderRoute: typeof DashboardAuthedAdminExamsExamIdReviewsRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/exams/$examId/sessions/': {
      id: '/dashboard/_authed/admin/exams/$examId/sessions/'
      path: '/admin/exams/$examId/sessions'
      fullPath: '/dashboard/admin/exams/$examId/sessions/'
      preLoaderRoute: typeof DashboardAuthedAdminExamsExamIdSessionsIndexRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
    '/dashboard/_authed/admin/exams/$examId/attempts/$attemptId': {
      id: '/dashboard/_authed/admin/exams/$examId/attempts/$attemptId'
      path: '/admin/exams/$examId/attempts/$attemptId'
      fullPath: '/dashboard/admin/exams/$examId/attempts/$attemptId'
      preLoaderRoute: typeof DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRouteImport
      parentRoute: typeof DashboardAuthedRoute
    }
  }
}

interface DashboardAuthedRouteChildren {
  DashboardAuthedAdminIndexRoute: typeof DashboardAuthedAdminIndexRoute
  DashboardAuthedTeamIndexRoute: typeof DashboardAuthedTeamIndexRoute
  DashboardAuthedAdminTeamsTeamIdRoute: typeof DashboardAuthedAdminTeamsTeamIdRoute
  DashboardAuthedAdminCompetitionsIndexRoute: typeof DashboardAuthedAdminCompetitionsIndexRoute
  DashboardAuthedAdminExamsIndexRoute: typeof DashboardAuthedAdminExamsIndexRoute
  DashboardAuthedAdminScoreboardIndexRoute: typeof DashboardAuthedAdminScoreboardIndexRoute
  DashboardAuthedAdminSubmissionsIndexRoute: typeof DashboardAuthedAdminSubmissionsIndexRoute
  DashboardAuthedAdminTeamsIndexRoute: typeof DashboardAuthedAdminTeamsIndexRoute
  DashboardAuthedAdminExamsExamIdReviewsRoute: typeof DashboardAuthedAdminExamsExamIdReviewsRoute
  DashboardAuthedTeamExamExamIdReviewRoute: typeof DashboardAuthedTeamExamExamIdReviewRoute
  DashboardAuthedAdminExamsExamIdIndexRoute: typeof DashboardAuthedAdminExamsExamIdIndexRoute
  DashboardAuthedTeamExamExamIdIndexRoute: typeof DashboardAuthedTeamExamExamIdIndexRoute
  DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute: typeof DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute
  DashboardAuthedAdminExamsExamIdSessionsIndexRoute: typeof DashboardAuthedAdminExamsExamIdSessionsIndexRoute
}

const DashboardAuthedRouteChildren: DashboardAuthedRouteChildren = {
  DashboardAuthedAdminIndexRoute: DashboardAuthedAdminIndexRoute,
  DashboardAuthedTeamIndexRoute: DashboardAuthedTeamIndexRoute,
  DashboardAuthedAdminTeamsTeamIdRoute: DashboardAuthedAdminTeamsTeamIdRoute,
  DashboardAuthedAdminCompetitionsIndexRoute:
    DashboardAuthedAdminCompetitionsIndexRoute,
  DashboardAuthedAdminExamsIndexRoute: DashboardAuthedAdminExamsIndexRoute,
  DashboardAuthedAdminScoreboardIndexRoute:
    DashboardAuthedAdminScoreboardIndexRoute,
  DashboardAuthedAdminSubmissionsIndexRoute:
    DashboardAuthedAdminSubmissionsIndexRoute,
  DashboardAuthedAdminTeamsIndexRoute: DashboardAuthedAdminTeamsIndexRoute,
  DashboardAuthedAdminExamsExamIdReviewsRoute:
    DashboardAuthedAdminExamsExamIdReviewsRoute,
  DashboardAuthedTeamExamExamIdReviewRoute:
    DashboardAuthedTeamExamExamIdReviewRoute,
  DashboardAuthedAdminExamsExamIdIndexRoute:
    DashboardAuthedAdminExamsExamIdIndexRoute,
  DashboardAuthedTeamExamExamIdIndexRoute:
    DashboardAuthedTeamExamExamIdIndexRoute,
  DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute:
    DashboardAuthedAdminExamsExamIdAttemptsAttemptIdRoute,
  DashboardAuthedAdminExamsExamIdSessionsIndexRoute:
    DashboardAuthedAdminExamsExamIdSessionsIndexRoute,
}

const DashboardAuthedRouteWithChildren = DashboardAuthedRoute._addFileChildren(
  DashboardAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardAuthedRoute: DashboardAuthedRouteWithChildren,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthRegisterTeamIdCompletedRoute: AuthRegisterTeamIdCompletedRoute,
  AuthRegisterTeamIdIndexRoute: AuthRegisterTeamIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
